version: "3"

volumes:
  pgadmin_data: {}

services:
  acc-serv1:
    container_name: acc-serv1
    image: acc-serv1
    env_file: .env
    ports:
      - "8001:8081"
    build:
      context: ./
      dockerfile: Dockerfile.accountsService

  acc-serv2:
    container_name: acc-serv2
    image: acc-serv2
    env_file: .env2
    ports:
      - "8002:8081"
    build:
      context: ./
      dockerfile: Dockerfile.accountsService

  operations-serv1:
    container_name: operations-serv1
    image: operations-serv1
    env_file: .env
    ports:
      - "8010:8081"
    build:
      context: ./
      dockerfile: Dockerfile.operationsService

  fees-serv1:
    container_name: fees-serv1
    image: fees-serv1
    env_file: .env
    ports:
      - "8011:8081"
    build:
      context: ./
      dockerfile: Dockerfile.feesService

  cashbacks-serv1:
    container_name: cashbacks-serv1
    image: cashbacks-serv1
    env_file: .env
    ports:
      - "8012:8081"
    build:
      context: ./
      dockerfile: Dockerfile.cashbacksService

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -Xms128m -Xmx256m
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://127.0.0.1:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_HOSTNAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
